### ISSUE TITLE
USER STORY:  Basic setup 

### ISSUE THREAD

**Issue by MkPrfct9** [MkPrfct9/Hello#1]
As a developer, I need to install set up libraries so the project so that basic features are  implemented

## Acceptance Criteria
* basic skeleton project should be successfully created

# Tasks
- [x] Install Django and gunicorn
- [x] Install supporting libraries
- [x] Install Cloudinary Libraries
- [x] Create requirements file
- [x] Create Project
- [x] Create App
- [x] run server
