### ISSUE TITLE
USER STORY: Basic Skeleton setup 

### ISSUE THREAD

**Issue by MkPrfct9** [MkPrfct9/Hello#2]
In order to **create basic setup of the django application** as a **developer**, I can ** use django**

## Acceptance Criteria
* Django framework installed in gitpod successfully

# Tasks
- [x]  Type install command in terminal 
- [x]  Check for the directories in file area 
- [x] Type install libraries commands in terminal
