### ISSUE TITLE
USER STORY: Manage Settings

### ISSUE THREAD

**Issue by MkPrfct9** [MkPrfct9/Hello#4]
As a developer, I need to update the resources in settings so that images, style and scripts works on the website

## Acceptance Criteria
* the secret keys should be hidden

# Tasks
- [ ] Set up environ variables
- [ ] Hide secret keys from git pod
- [ ] Reference env.py
- [ ] Update DataBases Sections
- [ ] Add Cloudinary Libraries to installed apps
- [ ] Tell Django to use Cloudinary to store media and static files
- [ ] Link file to the templates directory in Heroku
- [ ] Change the templates directory to TEMPLATES_DIR
- [ ] Add Heroku Hostname to ALLOWED_HOSTS
