### ISSUE TITLE
USER STORY: Create Home App

### ISSUE THREAD

**Issue by MkPrfct9** [MkPrfct9/Hello#6]
As a **Site User** I can **open home page** so that I can **view the website**
  
  
## Acceptance Criteria
* path added in project level urls.py
* opens home page

# Tasks
- [ ] create index.html
- [ ] create urls.py
- [ ] create views.py
- [ ] add app to installed app in settings.py
